apiVersion: apps/v1
kind: Deployment
metadata:
  name: agriculture
  labels:
    app: agriculture
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agriculture
  template:
    metadata:
      labels:
        app: agriculture
    spec:
      containers:
      - name: agriculture
        image: hatakekakashihk/sih-agriculture:latest
        imagePullPolicy: Always
        ports:
        - name: agriculture-port
          containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: agriculture-service
  labels:
    app: agriculture
spec:
  selector:
    app: agriculture
  ports:
  - name: agriculture-port
    port: 8000
    targetPort: 8000
  type: ClusterIP