---
apiVersion: v1
kind: Service
metadata:
  name: agriculture-service
  labels:
    app: agriculture
spec:
  selector:
    app: agriculture
  ports:
  - name: agri-port
    port: 8000
    targetPort: 8000
  type: ClusterIP