---
apiVersion: v1
kind: Service
metadata:
  name: classification-service
  labels:
    app: classification
spec:
  selector:
    app: classification
  ports:
  - name: class-port
    port: 5000
    targetPort: 5000
  type: ClusterIP